# Generated by Django 5.1.15 on 2026-05-08 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('kind', models.CharField(choices=[('usb', 'USB'), ('tcp', 'TCP/IP'), ('serial', 'Serial'), ('virtual', 'Виртуальный (файл)')], max_length=16)),
                ('address', models.CharField(blank=True, max_length=128)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='printers', to='users.restaurant')),
            ],
            options={
                'verbose_name': 'Принтер',
                'verbose_name_plural': 'Принтеры',
                'db_table': 'printers',
            },
        ),
        migrations.CreateModel(
            name='PrintJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('guest_receipt', 'Гостевой чек')], default='guest_receipt', max_length=24)),
                ('status', models.CharField(choices=[('pending', 'В очереди'), ('printing', 'Печатается'), ('done', 'Готово'), ('failed', 'Ошибка'), ('retrying', 'Повтор')], db_index=True, default='pending', max_length=12)),
                ('payload', models.JSONField(default=dict)),
                ('retries', models.PositiveSmallIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('scheduled_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='print_jobs', to='orders.order')),
                ('printer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='printing.printer')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_jobs', to='users.restaurant')),
            ],
            options={
                'verbose_name': 'Задание печати',
                'verbose_name_plural': 'Задания печати',
                'db_table': 'print_jobs',
                'ordering': ['-scheduled_at'],
            },
        ),
    ]
