# Generated by Django 5.1.15 on 2026-05-08 07:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='printjob',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='printjob',
            name='scheduled_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='printjob',
            name='status',
            field=models.CharField(choices=[('pending', 'В очереди'), ('printing', 'Печатается'), ('done', 'Готово'), ('failed', 'Ошибка (повтор)'), ('dead', 'Не доставлено')], db_index=True, default='pending', max_length=12),
        ),
    ]
