# Generated by Django 5.1.15 on 2026-05-09 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printing', '0002_printjob_created_at_alter_printjob_scheduled_at_and_more'),
        ('users', '0002_restaurant_address_restaurant_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='printer',
            name='paper_size',
            field=models.CharField(choices=[('58mm', '58 мм'), ('76mm', '76 мм'), ('80mm', '80 мм')], default='80mm', help_text='Ширина термобумаги — влияет на ширину строки ESC/POS-чека', max_length=8),
        ),
        migrations.AlterField(
            model_name='printjob',
            name='kind',
            field=models.CharField(choices=[('guest_receipt', 'Гостевой чек'), ('kitchen_order', 'Заказ на кухню'), ('bar_order', 'Заказ в бар'), ('pre_bill', 'Пре-чек'), ('refund_receipt', 'Чек возврата')], default='guest_receipt', max_length=24),
        ),
        migrations.CreateModel(
            name='PrintStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('system_code', models.CharField(blank=True, default='', help_text='cashier / kitchen для системных станций; пусто для обычных цехов', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('printer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stations', to='printing.printer')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_stations', to='users.restaurant')),
            ],
            options={
                'verbose_name': 'Цех / станция печати',
                'verbose_name_plural': 'Цеха / станции печати',
                'db_table': 'print_stations',
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
