# Generated by Django 5.1.15 on 2026-05-10 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printing', '0004_alter_printjob_kind_z_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printjob',
            name='kind',
            field=models.CharField(choices=[('guest_receipt', 'Гостевой чек'), ('kitchen_order', 'Заказ на кухню'), ('bar_order', 'Заказ в бар'), ('pre_bill', 'Пре-чек'), ('refund_receipt', 'Чек возврата'), ('z_report', 'Z-отчёт по смене'), ('cancel_runner', 'Бегунок отмены')], default='guest_receipt', max_length=24),
        ),
    ]
