# Generated by Django 5.1.15 on 2026-05-10 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_restaurant_address_restaurant_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='receipt_copies',
            field=models.PositiveSmallIntegerField(default=1, help_text='Сколько копий чека печатать при close_order (1-5)'),
        ),
    ]
