# Generated by Django 5.1.15 on 2026-05-10 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_restaurant_receipt_copies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('cashier', 'Кассир'), ('waiter', 'Официант'), ('cook', 'Повар')], default='waiter', max_length=16),
        ),
    ]
