# Generated by Django 5.1.15 on 2026-05-10 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printing', '0005_alter_printjob_kind'),
        ('users', '0004_kitchen_kds'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='kitchen_enabled',
            field=models.BooleanField(default=True, help_text='Если False — позиции автоматически READY при создании заказа'),
        ),
        migrations.AddField(
            model_name='user',
            name='kitchen_station',
            field=models.ForeignKey(blank=True, help_text='Только для роли cook: фильтр KDS по PrintStation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cooks', to='printing.printstation'),
        ),
    ]
