# Generated by Django 5.1.15 on 2026-05-10 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_restaurant_kitchen_enabled_user_kitchen_station'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='app_version',
            field=models.CharField(blank=True, help_text='Версия POS-клиента, который пингует', max_length=32),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='last_heartbeat_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Последний heartbeat от POS-клиента', null=True),
        ),
    ]
