# Generated by Django 5.1.15 on 2026-05-10 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_license_foundation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='permissions',
            field=models.JSONField(blank=True, default=list, help_text='Список permission-keys или [] для использования дефолтов роли'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('cashier', 'Кассир'), ('waiter', 'Официант'), ('cook', 'Повар'), ('manager', 'Менеджер')], default='waiter', max_length=16),
        ),
    ]
