# Generated by Django 5.1.15 on 2026-05-10 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_permissions_manager_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='manager_override_threshold_tjs',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Сумма заказа от которой отмена требует PIN менеджера. 0 = всегда без override.', max_digits=10),
        ),
    ]
