# Generated by Django 5.1.15 on 2026-05-10 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_manager_override_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='auto_open_cash_drawer',
            field=models.BooleanField(default=False, help_text='Автоматически открывать денежный ящик после печати чека'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='receipt_footer',
            field=models.TextField(blank=True, default='Спасибо за визит!', help_text='Подвал чека. Поддерживает переносы строк.'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='receipt_header_extra',
            field=models.TextField(blank=True, help_text='Доп. строки в шапке чека (после name/address/phone)'),
        ),
    ]
