# Generated by Django 5.1.15 on 2026-05-11 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_receipt_customization'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='api_key',
            field=models.CharField(blank=True, db_index=True, help_text='Секретный ключ для аутентификации restaurant-сервера в vendor cloud', max_length=128),
        ),
    ]
