# Generated by Django 5.1.15 on 2026-05-11 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_restaurant_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='0 = не учитывается в табеле', max_digits=10, verbose_name='Ставка за час'),
        ),
    ]
