# Generated by Django 5.1.15 on 2026-05-12 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_hourly_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='supply_allow_negative',
            field=models.BooleanField(default=False, help_text='Разрешать выдачу хозтоваров при нулевом или отрицательном остатке'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='tech_cards_enabled',
            field=models.BooleanField(default=True, help_text='Глобально включает автосписание ингредиентов по техкартам'),
        ),
    ]
