# Generated by Django 5.1.15 on 2026-05-12 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_restaurant_supply_allow_negative_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='printer_virtual_mode',
            field=models.BooleanField(default=False, help_text='Force-virtual: все принтеры пишут в файл вместо физ. печати'),
        ),
    ]
