# Generated by Django 5.1.15 on 2026-05-10 10:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0006_license_foundation'),
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('trial', 'Триал'), ('start', 'Старт'), ('business', 'Бизнес'), ('pro', 'Про')], default='trial', max_length=12)),
                ('license_key', models.CharField(blank=True, db_index=True, help_text='Уникальный ключ лицензии (генерим UUID, для offline-активации)', max_length=64)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Дата активации (для триала — установка)')),
                ('expires_at', models.DateTimeField(help_text='Дата окончания. После + grace дней — read-only.')),
                ('is_blocked', models.BooleanField(db_index=True, default=False, help_text='Принудительная блокировка (за неуплату). Игнорирует grace.')),
                ('block_reason', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True, help_text='Внутренние заметки вендора (контакт, история платежей)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='license', to='users.restaurant')),
            ],
            options={
                'verbose_name': 'Лицензия',
                'verbose_name_plural': 'Лицензии',
                'db_table': 'licenses',
            },
        ),
    ]
