# Generated by Django 5.1.15 on 2026-05-11 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0002_backfill_existing_restaurants'),
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseTokenCache',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('token', models.TextField(help_text='JWT, полученный от cloud /license/issue_token/')),
                ('claims', models.JSONField(default=dict, help_text='Декодированный payload JWT — основа для _enforce_license')),
                ('plan', models.CharField(blank=True, max_length=24)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_blocked', models.BooleanField(default=False)),
                ('block_reason', models.CharField(blank=True, max_length=255)),
                ('fetched_at', models.DateTimeField(auto_now=True, help_text='Когда был последний успешный refresh от cloud')),
            ],
            options={
                'verbose_name': 'Кэш лицензионного токена',
                'verbose_name_plural': 'Кэш лицензионных токенов',
                'db_table': 'license_token_cache',
            },
        ),
    ]
