# Generated by Django 5.1.15 on 2026-05-29 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0003_license_token_cache'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='activated_at',
            field=models.DateTimeField(blank=True, help_text='Когда POS впервые активировался на этой машине.', null=True),
        ),
        migrations.AddField(
            model_name='license',
            name='hardware_uuid',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Windows BIOS UUID привязанной машины. Пустое = ещё не активирована. Сбросить — для перепривязки при смене железа.', max_length=64),
        ),
    ]
