# Generated by Django 5.1.15 on 2026-05-08 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IdempotencyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=128, unique=True)),
                ('method', models.CharField(max_length=8)),
                ('path', models.CharField(max_length=255)),
                ('user_id', models.BigIntegerField(blank=True, null=True)),
                ('response_status', models.PositiveSmallIntegerField()),
                ('response_body', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Idempotency record',
                'verbose_name_plural': 'Idempotency records',
                'indexes': [models.Index(fields=['created_at'], name='common_idem_created_77f091_idx')],
            },
        ),
    ]
