# Generated by Django 5.1.15 on 2026-05-11 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0010_restaurant_api_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingTelemetrySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_id', models.PositiveIntegerField(db_index=True)),
                ('business_date', models.DateField()),
                ('captured_at', models.DateTimeField()),
                ('payload', models.JSONField(help_text='Готовый payload для POST /api/v1/telemetry/push/')),
                ('attempts', models.PositiveSmallIntegerField(default=0, help_text='Сколько раз пытались отправить — для exp.backoff')),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Pending telemetry',
                'verbose_name_plural': 'Pending telemetry',
                'db_table': 'pending_telemetry_snapshots',
                'ordering': ['business_date', 'captured_at'],
                'unique_together': {('restaurant_id', 'business_date')},
            },
        ),
        migrations.CreateModel(
            name='TelemetrySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_date', models.DateField(db_index=True, help_text='Календарная дата в TZ ресторана. Один snapshot/день.')),
                ('captured_at', models.DateTimeField(help_text='Когда ресторан сформировал этот snapshot')),
                ('received_at', models.DateTimeField(auto_now=True, help_text='Когда cloud получил этот push')),
                ('daily_revenue', models.DecimalField(decimal_places=2, default=0, help_text='Выручка с 00:00 до captured_at (закрытые заказы)', max_digits=14)),
                ('daily_orders_count', models.PositiveIntegerField(default=0, help_text='Сколько закрытых заказов сегодня')),
                ('mtd_revenue', models.DecimalField(decimal_places=2, default=0, help_text='Накопительно с 1-го числа месяца (month-to-date)', max_digits=14)),
                ('last_order_at', models.DateTimeField(blank=True, help_text='Когда был последний закрытый заказ (любой день)', null=True)),
                ('open_shifts_count', models.PositiveSmallIntegerField(default=0, help_text='Сколько открытых смен сейчас')),
                ('app_version', models.CharField(blank=True, help_text="Версия POS-клиента в момент push'а", max_length=32)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry_snapshots', to='users.restaurant')),
            ],
            options={
                'verbose_name': 'Телеметрия (день)',
                'verbose_name_plural': 'Телеметрия (по дням)',
                'db_table': 'telemetry_snapshots',
                'ordering': ['-business_date', 'restaurant_id'],
                'unique_together': {('restaurant', 'business_date')},
            },
        ),
    ]
