# Generated by Django 5.1.15 on 2026-05-11 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0001_initial'),
        ('users', '0010_restaurant_api_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantCatalogSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=dict, help_text='{restaurant, categories[], items[], totals}')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories_count', models.PositiveIntegerField(default=0)),
                ('items_count', models.PositiveIntegerField(default=0)),
                ('active_items_count', models.PositiveIntegerField(default=0)),
                ('restaurant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_snapshot', to='users.restaurant')),
            ],
            options={
                'verbose_name': 'Каталог меню ресторана',
                'verbose_name_plural': 'Каталоги меню ресторанов',
                'db_table': 'restaurant_catalog_snapshots',
            },
        ),
    ]
