# Generated by Django 5.1.15 on 2026-05-09 11:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0013_order_payment'),
        ('tables', '0003_table_group'),
        ('users', '0002_restaurant_address_restaurant_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=128)),
                ('customer_phone', models.CharField(blank=True, max_length=32)),
                ('party_size', models.PositiveSmallIntegerField(default=2)),
                ('scheduled_at', models.DateTimeField(db_index=True, help_text='Время на которое забронировано')),
                ('duration_min', models.PositiveSmallIntegerField(default=120, help_text='Сколько времени держим бронь (по умолчанию 2 часа)')),
                ('status', models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('confirmed', 'Подтверждена'), ('seated', 'Гости пришли'), ('cancelled', 'Отменена'), ('no_show', 'Не пришли')], db_index=True, default='pending', max_length=12)),
                ('notes', models.TextField(blank=True)),
                ('seated_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='users.restaurant')),
                ('seated_order', models.ForeignKey(blank=True, help_text='Заказ, который был открыт при посадке гостей', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='orders.order')),
                ('table', models.ForeignKey(help_text='Зарезервированный стол. PROTECT — не удалять стол с активной бронью.', on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='tables.table')),
            ],
            options={
                'verbose_name': 'Резервация',
                'verbose_name_plural': 'Резервации',
                'db_table': 'reservations',
                'ordering': ['-scheduled_at'],
                'indexes': [models.Index(fields=['restaurant', 'scheduled_at'], name='reservation_restaur_75c73c_idx'), models.Index(fields=['table', 'scheduled_at'], name='reservation_table_i_1306b4_idx')],
            },
        ),
    ]
