# Generated by Django 5.1.15 on 2026-05-08 12:47

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_restaurant_address_restaurant_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Открыта'), ('closed', 'Закрыта')], db_index=True, default='open', max_length=10)),
                ('number', models.PositiveIntegerField()),
                ('opening_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('closing_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('actual_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('opened_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('closed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shifts', to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='users.restaurant')),
            ],
            options={
                'verbose_name': 'Кассовая смена',
                'verbose_name_plural': 'Кассовые смены',
                'db_table': 'cash_shifts',
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='CashShiftOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('cash_in', 'Внесение'), ('cash_out', 'Изъятие')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='shifts.cashshift')),
            ],
            options={
                'verbose_name': 'Операция по смене',
                'verbose_name_plural': 'Операции по смене',
                'db_table': 'cash_shift_operations',
                'ordering': ['-created_at'],
            },
        ),
    ]
