# Generated by Django 5.1.15 on 2026-05-11 08:11

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0016_modifiers'),
        ('users', '0010_restaurant_api_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('unit', models.CharField(choices=[('kg', 'Килограмм'), ('g', 'Грамм'), ('l', 'Литр'), ('ml', 'Миллилитр'), ('piece', 'Штука'), ('pack', 'Упаковка'), ('bottle', 'Бутылка')], default='g', max_length=12)),
                ('avg_cost_per_unit', models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Средневзвешенная закупочная цена за 1 unit', max_digits=14)),
                ('low_stock_threshold', models.DecimalField(blank=True, decimal_places=3, help_text='Когда current_qty ≤ threshold — карточка подсвечивается', max_digits=14, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='users.restaurant')),
            ],
            options={
                'verbose_name': 'Ингредиент',
                'verbose_name_plural': 'Ингредиенты',
                'db_table': 'ingredients',
                'ordering': ['sort_order', 'name'],
                'unique_together': {('restaurant', 'name')},
            },
        ),
        migrations.CreateModel(
            name='IngredientStockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('purchase', 'Приёмка (накладная)'), ('consume', 'Расход при заказе'), ('produce_semi', 'Расход при варке полуфабриката'), ('waste', 'Списание (порча, бой)'), ('inventory_correct', 'Корректировка инвентаризацией'), ('return_to_supplier', 'Возврат поставщику'), ('manual', 'Ручная корректировка')], db_index=True, max_length=24)),
                ('qty_delta', models.DecimalField(decimal_places=3, help_text='Знаковая величина в единицах ингредиента. >0 приход, <0 расход.', max_digits=14)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=4, help_text='Цена за единицу в этой партии (только для purchase)', max_digits=14, null=True)),
                ('reason', models.CharField(blank=True, help_text='Свободная причина: «накладная #4521», «истёк срок», и т.д.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.ingredient')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='orders.order')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Движение остатка',
                'verbose_name_plural': 'Движения остатков',
                'db_table': 'ingredient_stock_movements',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['ingredient', 'created_at'], name='ingredient__ingredi_09b60b_idx')],
            },
        ),
    ]
