# Generated by Django 5.1.15 on 2026-05-11 08:28

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('orders', '0016_modifiers'),
        ('users', '0010_restaurant_api_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SemiFinishedType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('output_unit', models.CharField(choices=[('kg', 'Килограмм'), ('g', 'Грамм'), ('l', 'Литр'), ('ml', 'Миллилитр'), ('piece', 'Штука'), ('pack', 'Упаковка'), ('bottle', 'Бутылка')], default='kg', help_text='Единица готового полуфабриката', max_length=12)),
                ('yield_percent', models.DecimalField(decimal_places=2, default=Decimal('100'), help_text='Выход %: 100=идеально, 80=20%% потерь от сырья', max_digits=5)),
                ('avg_cost_per_unit', models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Средневзвешенная себестоимость 1 unit готового п/ф', max_digits=14)),
                ('low_stock_threshold', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semi_finished_types', to='users.restaurant')),
            ],
            options={
                'verbose_name': 'Полуфабрикат',
                'verbose_name_plural': 'Полуфабрикаты',
                'db_table': 'semi_finished_types',
                'ordering': ['sort_order', 'name'],
                'unique_together': {('restaurant', 'name')},
            },
        ),
        migrations.CreateModel(
            name='SemiFinishedStockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('produce', 'Произведено (варка партии)'), ('consume_for_dish', 'Расход в блюде'), ('waste', 'Списание'), ('inventory_correct', 'Корректировка инвентаризацией')], db_index=True, max_length=24)),
                ('qty_delta', models.DecimalField(decimal_places=3, max_digits=14)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=4, help_text='Себестоимость 1 unit этой партии (только produce)', max_digits=14, null=True)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='orders.order')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('semi_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.semifinishedtype')),
            ],
            options={
                'verbose_name': 'Движение п/ф',
                'verbose_name_plural': 'Движения п/ф',
                'db_table': 'semi_stock_movements',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['semi_type', 'created_at'], name='semi_stock__semi_ty_2bf3fa_idx')],
            },
        ),
        migrations.CreateModel(
            name='SemiFinishedRecipeLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_per_output', models.DecimalField(decimal_places=4, help_text='Сколько единиц компонента на 1 unit выхода п/ф', max_digits=14)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('ingredient', models.ForeignKey(blank=True, help_text='Сырой ингредиент (XOR с nested_semi)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.ingredient')),
                ('nested_semi', models.ForeignKey(blank=True, help_text='Другой п/ф (для рецептов «п/ф из п/ф»)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.semifinishedtype')),
                ('semi_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_lines', to='inventory.semifinishedtype')),
            ],
            options={
                'verbose_name': 'Строка рецепта',
                'verbose_name_plural': 'Строки рецептов',
                'db_table': 'semi_recipe_lines',
                'ordering': ['semi_type', 'sort_order'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('ingredient__isnull', False), ('nested_semi__isnull', True)), models.Q(('ingredient__isnull', True), ('nested_semi__isnull', False)), _connector='OR'), name='recipe_line_one_component_only')],
            },
        ),
    ]
