# Generated by Django 5.1.15 on 2026-05-12 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_semi'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='is_food',
            field=models.BooleanField(db_index=True, default=True, help_text='True = продукт, False = хозтовар (упаковка, моющие, и т.п.)'),
        ),
    ]
