# Generated by Django 5.1.15 on 2026-05-12 03:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_ingredient_is_food'),
        ('users', '0012_restaurant_supply_allow_negative_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_date', models.DateField()),
                ('is_food', models.BooleanField(blank=True, help_text='True = продукты, False = хозтовары, null = смешано', null=True)),
                ('note', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('applied', 'Проведён')], db_index=True, default='draft', max_length=10)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_checks', to='users.restaurant')),
            ],
            options={
                'verbose_name': 'Инвентаризация',
                'verbose_name_plural': 'Инвентаризации',
                'db_table': 'inventory_checks',
                'ordering': ['-check_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='InventoryCheckLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_qty', models.DecimalField(decimal_places=3, max_digits=14)),
                ('actual_qty', models.DecimalField(decimal_places=3, max_digits=14)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.ingredient')),
                ('inventory_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.inventorycheck')),
            ],
            options={
                'db_table': 'inventory_check_lines',
                'ordering': ['inventory_check', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StockReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_date', models.DateField()),
                ('number', models.CharField(blank=True, default='', help_text='Номер накладной (по документу поставщика)', max_length=64)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, help_text='Сумма по накладной (по сумме линий, авто-обновляется)', max_digits=14)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('applied', 'Проведён')], db_index=True, default='draft', max_length=10)),
                ('note', models.TextField(blank=True, default='')),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_receipts', to='users.restaurant')),
            ],
            options={
                'verbose_name': 'Накладная',
                'verbose_name_plural': 'Накладные',
                'db_table': 'inventory_stock_receipts',
                'ordering': ['-receipt_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StockReceiptLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=3, max_digits=14)),
                ('unit_cost', models.DecimalField(decimal_places=4, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.ingredient')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.stockreceipt')),
            ],
            options={
                'db_table': 'inventory_stock_receipt_lines',
                'ordering': ['receipt', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StockWriteoff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writeoff_date', models.DateField()),
                ('reason', models.CharField(choices=[('spoilage', 'Порча'), ('breakage', 'Бой/поломка'), ('expired', 'Просрочка'), ('tasting', 'Дегустация'), ('other', 'Прочее')], default='spoilage', max_length=12)),
                ('note', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('applied', 'Проведён')], db_index=True, default='draft', max_length=10)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_writeoffs', to='users.restaurant')),
            ],
            options={
                'verbose_name': 'Списание',
                'verbose_name_plural': 'Списания',
                'db_table': 'inventory_stock_writeoffs',
                'ordering': ['-writeoff_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StockWriteoffLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=3, max_digits=14)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.ingredient')),
                ('writeoff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.stockwriteoff')),
            ],
            options={
                'db_table': 'inventory_stock_writeoff_lines',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('phone', models.CharField(blank=True, default='', max_length=32)),
                ('contact_person', models.CharField(blank=True, default='', max_length=128)),
                ('note', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='users.restaurant')),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
                'db_table': 'inventory_suppliers',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='stockreceipt',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='inventory.supplier'),
        ),
        migrations.CreateModel(
            name='SupplyExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=3, max_digits=14)),
                ('reason', models.CharField(choices=[('to_hall', 'Выдано в зал'), ('to_kitchen', 'Выдано на кухню'), ('to_bar', 'Выдано в бар'), ('household', 'Хозяйственные нужды'), ('spoilage', 'Порча/негодное'), ('other', 'Прочее')], default='household', max_length=12)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.ingredient')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supply_expenses', to='users.restaurant')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Расход хозтовара',
                'verbose_name_plural': 'Расходы хозтоваров',
                'db_table': 'inventory_supply_expenses',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='inventorycheck',
            index=models.Index(fields=['restaurant', '-check_date'], name='inventory_c_restaur_0ddbef_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorycheck',
            index=models.Index(fields=['restaurant', 'status'], name='inventory_c_restaur_8b620f_idx'),
        ),
        migrations.AddIndex(
            model_name='stockwriteoff',
            index=models.Index(fields=['restaurant', '-writeoff_date'], name='inventory_s_restaur_c7bb52_idx'),
        ),
        migrations.AddIndex(
            model_name='stockwriteoff',
            index=models.Index(fields=['restaurant', 'status'], name='inventory_s_restaur_cfcf96_idx'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['restaurant', 'is_active'], name='inventory_s_restaur_e604d3_idx'),
        ),
        migrations.AddIndex(
            model_name='stockreceipt',
            index=models.Index(fields=['restaurant', '-receipt_date'], name='inventory_s_restaur_9c4551_idx'),
        ),
        migrations.AddIndex(
            model_name='stockreceipt',
            index=models.Index(fields=['restaurant', 'status'], name='inventory_s_restaur_8a2785_idx'),
        ),
        migrations.AddIndex(
            model_name='supplyexpense',
            index=models.Index(fields=['restaurant', '-created_at'], name='inventory_s_restaur_c5eb88_idx'),
        ),
        migrations.AddIndex(
            model_name='supplyexpense',
            index=models.Index(fields=['ingredient', '-created_at'], name='inventory_s_ingredi_18afab_idx'),
        ),
    ]
