# Generated by Django 5.1.15 on 2026-05-11 12:57

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0011_user_hourly_rate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('hours_worked', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Использованная ставка (среднее по TimeEntry.hourly_rate_snapshot)', max_digits=10)),
                ('base_salary', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='hours_worked × hourly_rate', max_digits=12)),
                ('bonuses', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('deductions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='base_salary + bonuses - deductions', max_digits=12)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('finalized', 'Финализирован'), ('paid', 'Выплачено')], db_index=True, default='draft', max_length=12)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('paid_operation_id', models.PositiveIntegerField(blank=True, help_text='ID FinancialOperation (Phase 3, пока soft-ref)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_periods', to='users.restaurant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_periods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Период зарплаты',
                'verbose_name_plural': 'Периоды зарплат',
                'db_table': 'payroll_periods',
                'ordering': ['-period_start'],
                'indexes': [models.Index(fields=['restaurant', 'user', '-period_start'], name='payroll_per_restaur_9b5505_idx'), models.Index(fields=['restaurant', 'status'], name='payroll_per_restaur_20fe8f_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('period_end__gte', models.F('period_start'))), name='payroll_period_end_gte_start')],
            },
        ),
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clock_in', models.DateTimeField()),
                ('clock_out', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Открыта'), ('closed', 'Закрыта'), ('auto_closed', 'Закрыта автоматом')], db_index=True, default='open', max_length=12)),
                ('hourly_rate_snapshot', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Ставка/час на момент clock_in (snapshot)', max_digits=10)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to='users.restaurant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='time_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Запись табеля',
                'verbose_name_plural': 'Записи табеля',
                'db_table': 'payroll_time_entries',
                'ordering': ['-clock_in'],
                'indexes': [models.Index(fields=['restaurant', 'user', '-clock_in'], name='payroll_tim_restaur_cf995f_idx'), models.Index(fields=['restaurant', 'status'], name='payroll_tim_restaur_9ee729_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('clock_out__isnull', True), ('clock_out__gte', models.F('clock_in')), _connector='OR'), name='time_entry_clock_out_after_in')],
            },
        ),
    ]
