# Generated by Django 5.1.15 on 2026-05-08 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_shift'),
        ('shifts', '0001_initial'),
        ('users', '0002_restaurant_address_restaurant_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RefundOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('reason', models.TextField()),
                ('idempotency_key', models.UUIDField(db_index=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds_made', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='orders.order')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='users.restaurant')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='shifts.cashshift')),
            ],
            options={
                'verbose_name': 'Возврат',
                'verbose_name_plural': 'Возвраты',
                'db_table': 'refund_operations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RefundedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField()),
                ('price_at_refund', models.DecimalField(decimal_places=2, max_digits=14)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='orders.orderitem')),
                ('refund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.refundoperation')),
            ],
            options={
                'verbose_name': 'Возвращённая позиция',
                'verbose_name_plural': 'Возвращённые позиции',
                'db_table': 'refunded_items',
                'ordering': ['id'],
            },
        ),
    ]
