# Generated by Django 5.1.15 on 2026-05-08 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_refundoperation_refundeditem'),
        ('users', '0002_restaurant_address_restaurant_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancelReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('item', 'Отмена позиции'), ('order', 'Отмена заказа'), ('refund', 'Возврат')], db_index=True, max_length=10)),
                ('label', models.CharField(max_length=128)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancel_reasons', to='users.restaurant')),
            ],
            options={
                'verbose_name': 'Причина отмены',
                'verbose_name_plural': 'Причины отмены',
                'db_table': 'cancel_reasons',
                'ordering': ['kind', 'sort_order', 'label'],
                'unique_together': {('restaurant', 'kind', 'label')},
            },
        ),
    ]
