# Generated by Django 5.1.15 on 2026-05-08 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_seed_cancel_reasons'),
        ('users', '0002_restaurant_address_restaurant_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('discount', 'Скидка'), ('service', 'Сервисный сбор')], default='discount', max_length=10)),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('kind', models.CharField(choices=[('percent', 'Процент'), ('fixed', 'Фиксированная')], default='percent', max_length=10)),
                ('value', models.DecimalField(decimal_places=2, help_text='Процент 0–100 либо фиксированная сумма', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='users.restaurant')),
            ],
            options={
                'verbose_name': 'Скидка',
                'verbose_name_plural': 'Скидки',
                'db_table': 'discounts',
                'ordering': ['type', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PaymentProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('kind', models.CharField(choices=[('cash', 'Наличные'), ('card', 'Банковская карта'), ('qr', 'QR-оплата'), ('wallet', 'Мобильный кошелёк'), ('transfer', 'Перевод')], db_index=True, max_length=10)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('commission_pct', models.DecimalField(decimal_places=2, default=0, help_text='Комиссия в %', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_providers', to='users.restaurant')),
            ],
            options={
                'verbose_name': 'Способ оплаты',
                'verbose_name_plural': 'Способы оплаты',
                'db_table': 'payment_providers',
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
