# Generated by Django 5.1.15 on 2026-05-09 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_seed_payments_discounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='service_charge_pct',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Сервисный сбор в %, snapshot из настроек на момент создания', max_digits=5),
        ),
    ]
