# Generated by Django 5.1.15 on 2026-05-09 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_service_charge_pct'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='applied_discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_orders', to='orders.discount'),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_kind',
            field=models.CharField(blank=True, help_text='percent | fixed (snapshot из Discount.kind на момент применения)', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Значение скидки snapshot (% или TJS). 0 = скидка не применена', max_digits=14),
        ),
    ]
