# Generated by Django 5.1.15 on 2026-05-09 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_applied_discount_order_discount_kind_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='note',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
