# Generated by Django 5.1.15 on 2026-05-09 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_orderitem_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='archived_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
