# Generated by Django 5.1.15 on 2026-05-09 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_order_archived_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('cash', 'Наличные'), ('card', 'Карта'), ('transfer', 'Перевод')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order')),
            ],
            options={
                'verbose_name': 'Платёж по заказу',
                'verbose_name_plural': 'Платежи по заказам',
                'db_table': 'order_payments',
                'ordering': ['id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='orderpayment_amount_positive')],
            },
        ),
    ]
