# Generated by Django 5.1.15 on 2026-05-10 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_order_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tip_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Чаевые гостя в валюте заказа', max_digits=14),
        ),
    ]
