# Generated by Django 5.1.15 on 2026-05-10 06:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_order_tip_amount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='cooked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='kitchen_status',
            field=models.CharField(choices=[('new', 'Новая'), ('cooking', 'Готовится'), ('ready', 'Готово'), ('served', 'Выдано')], db_index=True, default='new', max_length=12),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='ready_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='served_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='started_cooking_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
