# Generated by Django 5.1.15 on 2026-05-10 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_modifiers'),
        ('orders', '0015_kitchen_kds'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItemModifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_at_order', models.CharField(max_length=64)),
                ('price_delta_at_order', models.DecimalField(decimal_places=2, max_digits=14)),
                ('group_name_at_order', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modifier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='menu.modifier')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifiers', to='orders.orderitem')),
            ],
            options={
                'verbose_name': 'Модификатор позиции',
                'verbose_name_plural': 'Модификаторы позиций',
                'db_table': 'order_item_modifiers',
                'ordering': ['id'],
            },
        ),
    ]
