# Generated by Django 5.1.15 on 2026-05-12 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_modifiers'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='sent_to_kitchen_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
