# Generated by Django 5.1.15 on 2026-05-25 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_backfill_sent_to_kitchen_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='consumed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
