# Generated by Django 5.1.15 on 2026-05-09 11:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0002_table_current_order'),
        ('users', '0002_restaurant_address_restaurant_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='status',
            field=models.CharField(choices=[('free', 'Свободен'), ('occupied', 'Занят'), ('bill_requested', 'Счёт'), ('merged', 'Объединён')], db_index=True, default='free', max_length=16),
        ),
        migrations.CreateModel(
            name='TableGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Опциональное имя группы; если пусто — UI генерирует «5+6»', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('closed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('primary_table', models.ForeignKey(blank=True, help_text='Стол, на котором висит current_order группы.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_in_groups', to='tables.table')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_groups', to='users.restaurant')),
            ],
            options={
                'verbose_name': 'Группа столов',
                'verbose_name_plural': 'Группы столов',
                'db_table': 'table_groups',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='table',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tables', to='tables.tablegroup'),
        ),
    ]
