# Generated by Django 5.1.15 on 2026-05-16 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0003_table_group'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='table',
            unique_together={('zone', 'number')},
        ),
    ]
