# Generated by Django 5.1.15 on 2026-05-17 07:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_backfill_sent_to_kitchen_at'),
        ('tables', '0004_alter_table_unique_together'),
        ('users', '0013_restaurant_printer_virtual_mode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='table',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='table',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddConstraint(
            model_name='table',
            constraint=models.UniqueConstraint(condition=models.Q(('is_archived', False)), fields=('zone', 'number'), name='unique_zone_number_active'),
        ),
    ]
