# Generated by Django 5.1.15 on 2026-05-17 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0005_table_soft_archive'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zone',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
