# Generated by Django 5.1.15 on 2026-05-11 13:00

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0002_semi'),
        ('menu', '0009_batch_cooking_log'),
        ('users', '0011_user_hourly_rate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AbcSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('menu', 'Меню'), ('inventory', 'Склад')], default='menu', max_length=12)),
                ('period_from', models.DateField()),
                ('period_to', models.DateField()),
                ('total_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_cogs', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_margin', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abc_snapshots', to='users.restaurant')),
            ],
            options={
                'verbose_name': 'ABC-снимок',
                'verbose_name_plural': 'ABC-снимки',
                'db_table': 'analytics_abc_snapshots',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AbcSnapshotLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_snapshot', models.CharField(max_length=255)),
                ('qty_sold', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14)),
                ('revenue', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('cogs', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('margin', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('revenue_share_pct', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Доля от total_revenue, 0..100', max_digits=6)),
                ('cumulative_share_pct', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6)),
                ('abc_class', models.CharField(default='C', max_length=1)),
                ('rank', models.PositiveIntegerField(default=0)),
                ('ingredient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.ingredient')),
                ('menu_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='menu.menuitem')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='analytics.abcsnapshot')),
            ],
            options={
                'verbose_name': 'Строка ABC-снимка',
                'verbose_name_plural': 'Строки ABC-снимков',
                'db_table': 'analytics_abc_snapshot_lines',
                'ordering': ['snapshot', 'rank'],
            },
        ),
        migrations.AddIndex(
            model_name='abcsnapshot',
            index=models.Index(fields=['restaurant', 'kind', '-created_at'], name='analytics_a_restaur_88a9ab_idx'),
        ),
    ]
