# Generated by Django 5.1.15 on 2026-05-09 03:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_restaurant_address_restaurant_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_full_name', models.CharField(blank=True, help_text='Snapshot имени пользователя на момент действия', max_length=128)),
                ('action', models.CharField(choices=[('login', 'Вход'), ('logout', 'Выход'), ('pin_change', 'Смена PIN'), ('shift_open', 'Открытие смены'), ('shift_close', 'Закрытие смены'), ('cash_in', 'Внесение в кассу'), ('cash_out', 'Изъятие из кассы'), ('order_create', 'Создание заказа'), ('order_add_items', 'Добавление позиций'), ('order_cancel', 'Отмена заказа'), ('order_close', 'Закрытие заказа (оплата)'), ('order_transfer', 'Перенос на другой стол'), ('item_cancel', 'Отмена позиции'), ('bill_request', 'Запрос счёта'), ('discount_apply', 'Применение скидки'), ('discount_remove', 'Снятие скидки'), ('refund', 'Возврат'), ('user_create', 'Создание пользователя'), ('user_update', 'Изменение пользователя'), ('user_delete', 'Удаление пользователя'), ('settings_update', 'Изменение настроек')], db_index=True, max_length=24)),
                ('target_type', models.CharField(blank=True, db_index=True, max_length=32)),
                ('target_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_entries', to='users.restaurant')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Запись журнала',
                'verbose_name_plural': 'Журнал действий',
                'db_table': 'audit_entries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['restaurant', '-created_at'], name='audit_resto_date_idx'), models.Index(fields=['restaurant', 'action', '-created_at'], name='audit_resto_action_idx')],
            },
        ),
    ]
