# Generated by Django 5.1.15 on 2026-05-09 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_alter_auditentry_action_z_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditentry',
            name='action',
            field=models.CharField(choices=[('login', 'Вход'), ('logout', 'Выход'), ('pin_change', 'Смена PIN'), ('shift_open', 'Открытие смены'), ('shift_close', 'Закрытие смены'), ('z_report_printed', 'Печать Z-отчёта'), ('cash_in', 'Внесение в кассу'), ('cash_out', 'Изъятие из кассы'), ('order_create', 'Создание заказа'), ('order_add_items', 'Добавление позиций'), ('order_cancel', 'Отмена заказа'), ('order_close', 'Закрытие заказа (оплата)'), ('order_transfer', 'Перенос на другой стол'), ('item_cancel', 'Отмена позиции'), ('bill_request', 'Запрос счёта'), ('discount_apply', 'Применение скидки'), ('discount_remove', 'Снятие скидки'), ('refund', 'Возврат'), ('user_create', 'Создание пользователя'), ('user_update', 'Изменение пользователя'), ('user_delete', 'Удаление пользователя'), ('settings_update', 'Изменение настроек'), ('tables_merged', 'Объединение столов'), ('tables_unmerged', 'Разъединение столов')], db_index=True, max_length=24),
        ),
    ]
