# Generated by Django 5.1.15 on 2026-05-10 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0005_kitchen_kds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditentry',
            name='action',
            field=models.CharField(choices=[('login', 'Вход'), ('logout', 'Выход'), ('pin_change', 'Смена PIN'), ('shift_open', 'Открытие смены'), ('shift_close', 'Закрытие смены'), ('z_report_printed', 'Печать Z-отчёта'), ('cash_in', 'Внесение в кассу'), ('cash_out', 'Изъятие из кассы'), ('order_create', 'Создание заказа'), ('order_add_items', 'Добавление позиций'), ('order_cancel', 'Отмена заказа'), ('order_close', 'Закрытие заказа (оплата)'), ('order_transfer', 'Перенос на другой стол'), ('item_cancel', 'Отмена позиции'), ('bill_request', 'Запрос счёта'), ('discount_apply', 'Применение скидки'), ('discount_remove', 'Снятие скидки'), ('refund', 'Возврат'), ('user_create', 'Создание пользователя'), ('user_update', 'Изменение пользователя'), ('user_delete', 'Удаление пользователя'), ('settings_update', 'Изменение настроек'), ('manager_override', 'Подтверждение менеджера'), ('tables_merged', 'Объединение столов'), ('tables_unmerged', 'Разъединение столов'), ('kitchen_start_cooking', 'Кухня: взято в работу'), ('kitchen_mark_ready', 'Кухня: готово'), ('kitchen_mark_served', 'Кухня: выдано'), ('reservation_created', 'Создана резервация'), ('reservation_confirmed', 'Резервация подтверждена'), ('reservation_seated', 'Гости резервации пришли'), ('reservation_cancelled', 'Резервация отменена'), ('reservation_no_show', 'Гости резервации не пришли')], db_index=True, max_length=24),
        ),
    ]
