# Generated by Django 5.1.15 on 2026-05-09 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
        ('printing', '0003_printer_paper_size_alter_printjob_kind_printstation'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='print_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='printing.printstation'),
        ),
    ]
