# Generated by Django 5.1.15 on 2026-05-09 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_category_print_station'),
        ('users', '0002_restaurant_address_restaurant_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItemNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=64)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_notes', to='users.restaurant')),
            ],
            options={
                'verbose_name': 'Шаблон комментария',
                'verbose_name_plural': 'Шаблоны комментариев к блюдам',
                'db_table': 'menu_item_notes',
                'ordering': ['sort_order', 'label'],
                'unique_together': {('restaurant', 'label')},
            },
        ),
    ]
