# Generated by Django 5.1.15 on 2026-05-10 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_seed_item_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='stop_reason',
            field=models.CharField(blank=True, help_text='Причина снятия со стоп-листа (например, «Закончилась говядина»)', max_length=255),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='stop_until',
            field=models.DateField(blank=True, help_text='Дата когда блюдо снова станет доступным (опц.)', null=True),
        ),
    ]
