# Generated by Django 5.1.15 on 2026-05-10 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_menu_item_stop_list'),
        ('users', '0009_receipt_customization'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModifierGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('min_select', models.PositiveSmallIntegerField(default=0)),
                ('max_select', models.PositiveSmallIntegerField(default=1)),
                ('is_required', models.BooleanField(db_index=True, default=False)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifier_groups', to='users.restaurant')),
            ],
            options={
                'verbose_name': 'Группа модификаторов',
                'verbose_name_plural': 'Группы модификаторов',
                'db_table': 'menu_modifier_groups',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Modifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('price_delta', models.DecimalField(decimal_places=2, default=0, help_text='Доплата (>0) или скидка (<0) к цене блюда за единицу', max_digits=14)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifiers', to='menu.modifiergroup')),
            ],
            options={
                'verbose_name': 'Модификатор',
                'verbose_name_plural': 'Модификаторы',
                'db_table': 'menu_modifiers',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='menuitem',
            name='modifier_groups',
            field=models.ManyToManyField(blank=True, related_name='menu_items', to='menu.modifiergroup'),
        ),
        migrations.AddConstraint(
            model_name='modifiergroup',
            constraint=models.CheckConstraint(condition=models.Q(('min_select__lte', models.F('max_select'))), name='modgroup_min_le_max'),
        ),
        migrations.AlterUniqueTogether(
            name='modifiergroup',
            unique_together={('restaurant', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='modifier',
            unique_together={('group', 'name')},
        ),
    ]
