# Generated by Django 5.1.15 on 2026-05-10 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_modifiers'),
        ('users', '0009_receipt_customization'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='cogs',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Себестоимость единицы (для аналитики маржинальности)', max_digits=14),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='cook_time_min',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Время готовки в минутах (для таймера KDS)', null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='is_batch_cooking',
            field=models.BooleanField(default=False, help_text='Готовится партиями (плов на 20 порций утром)'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='is_purchased',
            field=models.BooleanField(default=False, help_text='Покупной товар (без техкарты) — кофе/снеки от поставщика'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='kind',
            field=models.CharField(choices=[('hot_kitchen', 'Горячий цех'), ('cold_kitchen', 'Холодный цех'), ('grill', 'Шашлычный / Гриль'), ('bar', 'Бар'), ('showcase', 'Витрина'), ('drink', 'Напиток'), ('dessert', 'Десерт')], db_index=True, default='hot_kitchen', help_text='Где/как готовится: горячий цех, бар, гриль и т.д.', max_length=16),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='low_stock_threshold',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Порог «заканчивается»: когда prepared_qty ≤ threshold карточка подсвечивается оранжевым', null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='prepared_qty',
            field=models.PositiveIntegerField(default=0, help_text='Сколько порций готово сейчас (для batch-блюд)'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='sale_step',
            field=models.PositiveIntegerField(default=0, help_text='Минимальный шаг продажи (50 г для весов; 0 = любой)'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='unit',
            field=models.CharField(choices=[('piece', 'Штука'), ('g', 'Грамм'), ('kg', 'Килограмм')], default='piece', help_text='Единица продажи: штука / граммы / кг', max_length=8),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='unit_size',
            field=models.PositiveIntegerField(default=1, help_text='Цена указана за N единиц: 1 шт / 100 г / 1 кг'),
        ),
        migrations.AddConstraint(
            model_name='menuitem',
            constraint=models.CheckConstraint(condition=models.Q(('is_purchased', True), ('is_batch_cooking', True), _negated=True), name='menuitem_not_purchased_and_batch'),
        ),
        migrations.AddConstraint(
            model_name='menuitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_size__gte', 1)), name='menuitem_unit_size_ge_1'),
        ),
    ]
