# Generated by Django 5.1.15 on 2026-05-11 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_semi'),
        ('menu', '0007_menuitem_kind_unit_batch'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItemTechCardLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_per_unit', models.DecimalField(decimal_places=4, help_text='Сколько единиц компонента на 1 порцию блюда', max_digits=14)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ingredient', models.ForeignKey(blank=True, help_text='Сырой ингредиент (XOR с nested_semi)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.ingredient')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tech_card_lines', to='menu.menuitem')),
                ('nested_semi', models.ForeignKey(blank=True, help_text='Полуфабрикат (XOR с ingredient)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.semifinishedtype')),
            ],
            options={
                'verbose_name': 'Строка техкарты',
                'verbose_name_plural': 'Строки техкарт',
                'db_table': 'menu_tech_card_lines',
                'ordering': ['menu_item', 'sort_order'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('ingredient__isnull', False), ('nested_semi__isnull', True)), models.Q(('ingredient__isnull', True), ('nested_semi__isnull', False)), _connector='OR'), name='techcard_line_one_component_only'), models.CheckConstraint(condition=models.Q(('qty_per_unit__gt', 0)), name='techcard_qty_positive')],
            },
        ),
    ]
