# Generated by Django 5.1.15 on 2026-05-11 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_tech_card'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchCookingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_delta', models.IntegerField(help_text='+N при заготовке, -N при расходе (всегда != 0)')),
                ('new_total', models.PositiveIntegerField(help_text='prepared_qty ПОСЛЕ применения qty_delta (clamped to ≥ 0)')),
                ('kind', models.CharField(choices=[('cook', 'Заготовка'), ('consume', 'Расход'), ('correct', 'Корректировка')], max_length=12)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_logs', to='menu.menuitem')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Лог заготовки',
                'verbose_name_plural': 'Логи заготовки',
                'db_table': 'menu_batch_cooking_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['menu_item', '-created_at'], name='menu_batch__menu_it_460fba_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('qty_delta', 0), _negated=True), name='batch_log_qty_delta_nonzero')],
            },
        ),
    ]
