# Generated by Django 5.1.15 on 2026-05-12 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_batch_cooking_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='auto_consume',
            field=models.BooleanField(default=True, help_text='Списывать по техкарте при close_order (выкл. = не списывать)'),
        ),
    ]
