# Generated by Django 5.1.15 on 2026-05-23 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0010_menuitem_auto_consume'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='allow_oversell',
            field=models.BooleanField(default=False, help_text='Разрешить продажу при нулевых остатках (override авто-стопа)'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='auto_stopped',
            field=models.BooleanField(db_index=True, default=False, help_text='Снято со стопа автоматически из-за пустого склада (≠ ручной стоп)'),
        ),
    ]
